---
name: module3_task2
on:
  push:
    # branches: [master]
    paths:
      - 'module3_task2/**'
  schedule:
    - cron: 0 5 * * *

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Clone and check out repo
        uses: actions/checkout@v3
        
      - name: Run setup script to install Hugo
        run: |
          cd module3_task2/
          ./setup.sh
                
      - name: Validation Makefile
        run: |
          cd module3_task2/
          make lint
          make build
          make package
          make unit-tests
          make integration-tests
          make validate
          
      - name: Build archive
        # If none of previous steps have failed, success returns true
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task2/awesome-website.zip
