---
name: module3_task3
on:
  push:
    branches: [main, master]
  schedule:
    - cron: 0 5 * * *

jobs:
  module3_task3:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone and check out repo
        uses: actions/checkout@v3

      - name: Run setup script to install Hugo
        run: |
          cd module3_task3/
          chmod 755 setup.sh
          ./setup.sh

      - name: Validation Makefile
        run: |
          cd module3_task3/
          make lint
          make build
          make POST_TITLE=Test POST_NAME='TestSuccess' post
          make unit-tests

      - name: Integration testing
        run: |
          cd module3_task3
          make validate
          make integration-tests
          make unit-tests
          make package
          make clean

      - name: Build archive
        # If none of previous steps have failed, success returns true
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task2/awesome-website.zip
