name: module3_task0
on:
  push:
    branches:
      - master
  schedule:
    # * is special character quote it
    # trigger the workflow every day at 5:30
    - cron: '30 5 * * *'

jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the help target
        uses: actions/checkout@v3
      - name: cd to directory containing symlink
        run: |
          cd module3_task0
          make help