---
name: module3_task1
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 5 * * *
jobs:
  module3_task1:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone and check out repo
        uses: actions/checkout@v3
      - name: Run setup script to install Hugo
        run: |
          cd module3_task1/
          chmod 755 setup.sh
          sudo ./setup.sh
        shell: bash
      - name: Use build in Makefile
        run: |
          cd module3_task1/
          sudo make build
      - name: Create new post
        run: |
          cd module3_task1/
          sudo make POST_TITLE="Test" POST_NAME="name" post
      - name: Clean up
        run: |
          cd module3_task1/
          sudo make clean
          
