---
name: module3_task0

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Navigate to project directory
        run: |
          cd module3_task0/
          make help
