---
name: module3_task1
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 5 * * *
    
permissions: read-all

jobs:
  module3_task1:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone and check out repo
        uses: actions/checkout@v3
      - name: Run setup script to install Hugo
        run: |
          cd module3_task1/
          chmod 755 setup.sh
          ./setup.sh
        shell: bash
      - name: Validation Makefile
        run: |
          cd module3_task1/
          make help
          make build
          make clean
          make POST_TITLE="Test" POST_NAME="name" post
