name: module3_task0
on:
  schedule:
  # Triggers the workflow every day at 5:30 UTC
  # * is a special character in YAML so you have to quote this string
    - cron: '30 5 * * *'
  push: null
  
jobs:
  runs-on: ubuntu-latest
  steps:
    -uses: actions/checkout@v2
    -name: Clone the repo and make help
     run:git clone https://github.com/mimi-fOlle/holbertonschool-validation.git
     run:make help
