---
name: module3_task1
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
jobs:
  module3_task1:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone and checkout the repo
        uses: actions/checkout@v2
      - name: Execute setup.sh
        run: |
          cd module3_task1/
          sudo ./setup.sh
          shell: bash
      - name: Execute build in Makefile
        run: |
          cd module3_task1/
          sudo make build
          