---
name: module3_task0
on:
  schedule:
    - cron: 30 5 * * *
  push:
    branches: -master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Makefile
        run: make help
        working-directory: module3_task0
