---
name: module3_task0
on:
  schedule:
    - cron: 30 5 * * *
  push:
    branches: -master
jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd module3_task0
      - run: make help
        working-directory: module3_task0
